---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: equilibrium-runner
  namespace: actions
spec:
  replicas: 1
  template:
    spec:
      repository: clibequilibrium/argocd_zenoh_docker_deployment
      env: []