{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zenoh.serviceAccountName" . }}
  labels:
{{ include "zenoh.labels" . | nindent 4 }}
{{- end -}}
