apiVersion: v1
kind: Service
metadata:
  name: {{ include "zenoh.fullname" . }}
  labels:
    {{- include "zenoh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: zenoh
  selector:
    {{- include "zenoh.selectorLabels" . | nindent 4 }}
