# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]
jobs:
  build:
    name: Building and Pushing the Image
    runs-on: my-custom-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: create-json
      #   id: create-json
      #   uses: jsdaniell/create-json@v1.2.1
      #   with:
      #     name: "zenoh.json5"
      #     json: ${{ secrets.ZENOH_CONFIG_JSON }}
      #     dir: .

      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and Push the Docker image
        env:
          REGISTRY: clibequilibrium
          REPOSITORY: zenoh_deployment
        run: |
          # Build a docker container and push it to ECR
          echo "Config value:"
          cat zenoh.json5
          git_hash=$(git rev-parse --short HEAD)
          docker build -t $REGISTRY/$REPOSITORY:$git_hash .
          echo "Pushing image to DockerHub..."
          echo "repo name: $REGISTRY/$REPOSITORY:$git_hash"
          docker push $REGISTRY/$REPOSITORY:$git_hash
          echo "::set-output name=image::$REGISTRY/$REPOSITORY:$git_hash"

      - name: Update Version
        run: |
          git_hash=$(git rev-parse --short HEAD)
          version=$(cat ./charts/zenoh/values.yaml | grep version: | awk '{print $2}')
          sed -i "s/$version/$git_hash/" ./charts/zenoh/values.yaml
          
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Version updated